version: '3'
services:
  gbms-strapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: "${REGISTRY}/${IMAGE}:latest"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: gbms-strapi-postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}

    #    volumes:
    #      - ./config:/opt/app/config
    #      - ./src:/opt/app/src
    #      - ./package.json:/opt/package.json
    #      - ./yarn.lock:/opt/yarn.lock
    #      - ./.env:/opt/app/.env
    #      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - gbms-strapi
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.gbms-strapi.rule=Host(`${TRAEFIK_HOST?Variable not set}`)
        - traefik.http.routers.gbms-strapi-http.entrypoints=http
        - traefik.http.routers.gbms-strapi-http.service=gbms-strapi
        - traefik.http.routers.gbms-strapi-http.rule=Host(`${TRAEFIK_HOST?Variable not set}`)
        - traefik.http.routers.gbms-strapi-http.middlewares=https-redirect
        - traefik.http.routers.gbms-strapi.entrypoints=https
        - traefik.http.routers.gbms-strapi.tls=true
        - traefik.http.routers.gbms-strapi.tls.certresolver=le
        - traefik.http.services.gbms-strapi.loadbalancer.server.port=1337
        - traefik.http.routers.gbms-strapi.service=gbms-strapi

  gbms-strapi-postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - gbms-strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - '5432:5432'
    networks:
      - gbms-strapi
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1

volumes:
  gbms-strapi-data:

networks:
  traefik-public:
    external: true
  gbms-strapi:
    driver: overlay
